- name: "安装 kafka"
  gather_facts: no
  hosts: kafka
  roles:
  - { role: kafka }
  tags:
  - kafka

- name: "启动 kafka"
  gather_facts: no
  hosts: kafka
  roles:
  - { role: kafka_manager, action: "kafka-server-start.sh -daemon config/server.properties"}
  tags:
  - kafka-server-start