- name: "停止 kafka"
  gather_facts: no
  hosts: kafka
  roles:
  - { role: kafka_manager, action: kafka-server-stop.sh}
  tags:
  - stop_kafka

- name: "删除 kafka"
  gather_facts: no
  hosts: kafka
  roles:
  - del_kafka
  tags:
  - del_kafka